name: gradlew_plugin
version: 0.0.1
language: android
description: Android anlayzer to check files quality.
tags:
 - android
 - format
 - analyzer
 - quality
 - plugin

public: true

# clone_in_docker: false

script_path: ./run.sh
